### ISSUE TITLE
Not working  

### ISSUE THREAD

**Issue by LeeHine1** [NochexDevTeam/WooCommerce#2]
Payment not coming through or registering on woocommerce   latest update have had to downgrade,  has anyone else reported i need some time to find problem if its a conflict with other Plugins

**Comment by NochexDevTeam** [comment]
Good Afternoon,

Apologies for our delayed response, 

We have now released a newer version of our module, and should address your issue. 

If this is not the case, Please get in touch and we will be more than happy to assist you.

Kind Regards
James Lugton - Nochex Technical Support
